### PR TITLE
Feature/domain models

### PR DESCRIPTION
**Pull request by lee-dhs-isobar**

### CODE REVIEW

**Comment by adam-dhs-isobar** [comment]
Thinking about this a little more, I think we should merge the User and Employee models together.  All employees should be able to login to the application and it probably doesn't make sense to separate the two.  Do you want to make those updates before merging?

**Comment by lee-dhs-isobar** [comment]
Sounds good, keep Employee or User?

**Comment by adam-dhs-isobar** [comment]
Let's go with User.

**Comment by lee-dhs-isobar** [comment]
updated, looks good?

**Pull request merged**
